name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./gradlew --no-parallel --no-daemon --build-cache build
